### ISSUE TITLE
datetime gets converted into date

### ISSUE THREAD

**Issue by loneharoon** [Nicktz/tbl2xts#1]
The function `tbl_xts()` converts datetime format of required index column to date format. How to preserve the same during conversion?

**Comment by Nicktz** [comment]
First, are you using the latest version of tbl2xts (version 0.1.1)? Secondly, what is the purpose of preserving your date column format when transforming to xts?

Could you draw up a mini working example for me to check on my side whether your issue might be worth exploring please. 

Nico

**Comment by loneharoon** [comment]
Yes, I am using version 0.1.1.

```
library(tbl2xts)
datetime <- seq(as.POSIXct('2016-01-01'),as.POSIXct('2016-02-01 23:59:59'), by = "2 hours")
tbl_data <-  tibble(date=datetime,data =rnorm(length(datetime),100,3)) 
xts_data  <- tbl_xts(tbl_data)

```
Now, compare output of `head(tbl_data)` and `head(xts_data)` and you will find how time information gets lost during coercion.

**Comment by Nicktz** [comment]
Issue has now been resolved. It normally takes a day or so to get on CRAN. In the meantime, download the working version and test if this resolves your problem please.

    library(devtools)
    install_github("Nicktz/tbl2xts")

You should be able to download version 0.1.2 in the next few days using install.packages.

Regards,

Nico
