### ISSUE TITLE
Keeping spreaded column names the same

### ISSUE THREAD

**Issue by Ljupch0** [Nicktz/tbl2xts#4]
Hi Nico,

Great package for working with Performance Analytics in a tidier way.

My question is whether the column names can be kept the same. For instance, if I'm spreading the security names, "Company XYZ" becomes "Company.XYZ_total_return". Is it possible to enforce no suffix, as well as no period for spaces? Ideally the final columns will be just "Company XYZ".

My next step is to `gather` or `pivot_longer` this result for continued work with dplyr, and this would make it less error prone compared to me rewriting the columns with the original names.

Thank you.

**Comment by Nicktz** [comment]
@Ljupch0 Hi - it's bothered me alot in the past as well, but it is unfortunately a native xts issue.

I've now built in a parameter that keeps column names the same - Colnames_Exact - which will be FALSE by default (for backward compatability).

Please download the latest github development version and test it out with the new argument (see README example with this argument) - let me know if it works for you. Also, you can set suffixes off with spread_name_pos = "NONE"

**Comment by Ljupch0** [comment]
Thank you for the quick reply and solution! I've downloaded the new github version, and the periods are gone. However when I set `spread_name_pos = "NONE"` I get `Note: Forced to use suffix for differentiation purposes, because length of cols_to_xts is larger than 1 & spread_by has been set: name`, and the columns still have the suffix. The length of `cols_to_xts` is 1, `cols_to_xts = c(total_return)`. Maybe this is a bug? I will write a reprex tomorrow to make this easier.

**Comment by Nicktz** [comment]
Hi, so that is not a bug.

The error is there to stop you having two columns with the same name.

E.g., see my readme examples on that.

As a quick illustration, if you have:

date      Tickers     Return     TRI
xxxx        AAA           0.12       -0.02
xxxx        BBB           0.02         0.01
yyyy        AAA           -0.01        -0.03
yyyy        BBB           0.06         0.03

If you now try and spread both Return and TRI - how will it differentiate
between AAA for Return and AAA for TRI without a suffix? That's why I force
a suffix there.

You are welcome to send me a mini-example of your data - if the above
doesn't apply I would be very interested to see an example to possibly
improve the code.

Thanks!

N

**Comment by Ljupch0** [comment]
I completely agree with the logic. I have found the issue. If the data is grouped, dplyr will include the grouping variable, so the length of  `N_xts_Cols <- tblData %>% select(!!cols_xts) %>% ncol()` will be 2, not 1 thus enforcing the suffix. See this example 
``` 
tibble(
  date = as.Date(c("2020-01-31", "2020-02-29", "2020-01-31", "2020-02-29")),
  tickers = c("AAA", "AAA", "BBB", "BBB"),
  return = c(-0.1, 0.02, 0.05, 0.04),
  TRI = c(-0.02, 0.01, -0.03, 0.03)
) %>% group_by(tickers) %>% tbl2xts::tbl_xts(., cols_to_xts = c(return), spread_by = "tickers")
```
I have a simple pull request that just ungroups the input data before proceeding.

**Comment by Nicktz** [comment]
Ah I see now yes - that's a great pick up.
It is fairly new dplyr behaviour that - definitely not ideal.
I've moved the explicit ungrouping higher and added a few warning checks too.
You can load the latest development version from github and it all should work out now.

**Comment by Ljupch0** [comment]
Great but I think the ungrouping should move even higher, before `N_xts_Cols <- tblData %>% select(!!cols_xts) %>% ncol()` is calculated.

**Comment by Nicktz** [comment]
Ah of course yes...
Checks out now.

**Comment by Ljupch0** [comment]
Perfect! Thank you for the quick replies, have a great day.
